### ISSUE TITLE
npm run start fails

### ISSUE THREAD

**Issue by dschuessler** [ByronHsu/Never-Blink#6]
```
$ npm run start

> @ start /Users/dennis/Documents/Developer/Repositories/Never-Blink
> python3 server.py

WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Serving Flask app "server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "server.py", line 226, in <module>
    keyfile=os.path.join('backend', 'server.key'), certfile=os.path.join('backend', 'server.crt'))
  File "/usr/local/lib/python3.7/site-packages/flask_socketio/__init__.py", line 524, in run
    use_reloader=use_reloader, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
TypeError: run_simple() got an unexpected keyword argument 'keyfile'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `python3 server.py`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dschuessler/.npm/_logs/2019-06-13T20_55_26_642Z-debug.log
```

Python 3.7.3
macOS 10.14.5

**Comment by ByronHsu** [comment]
Hi, did you try install ``eventlet`` or ``gevent and gevent-websocket``?
